
// Map of all possible district variations to their canonical key
export const DISTRICT_KEY_MAP: Record<string, string> = {
    // English
    'colombo': 'colombo',
    'gampaha': 'gampaha',
    'kalutara': 'kalutara',
    'kandy': 'kandy',
    'matale': 'matale',
    'nuwara eliya': 'nuwara_eliya',
    'nuwara-eliya': 'nuwara_eliya',
    'galle': 'galle',
    'matara': 'matara',
    'hambantota': 'hambantota',
    'jaffna': 'jaffna',
    'kilinochchi': 'kilinochchi',
    'mannar': 'mannar',
    'vavuniya': 'vavuniya',
    'mullaitivu': 'mullaitivu',
    'batticaloa': 'batticaloa',
    'ampara': 'ampara',
    'trincomalee': 'trincomalee',
    'kurunegala': 'kurunegala',
    'puttalam': 'puttalam',
    'anuradhapura': 'anuradhapura',
    'polonnaruwa': 'polonnaruwa',
    'badulla': 'badulla',
    'monaragala': 'monaragala',
    'ratnapura': 'ratnapura',
    'kegalle': 'kegalle',

    // Sinhala
    'කොළඹ': 'colombo',
    'ගම්පහ': 'gampaha',
    'කළුතර': 'kalutara',
    'මහනුවර': 'kandy',
    'මාතලේ': 'matale',
    'නුවරඑළිය': 'nuwara_eliya',
    'නුවර එළිය': 'nuwara_eliya',
    'ගාල්ල': 'galle',
    'මාතර': 'matara',
    'හම්බන්තොට': 'hambantota',
    'යාපනය': 'jaffna',
    'කිලිනොච්චිය': 'kilinochchi',
    'කිලිනොච්චි': 'kilinochchi',
    'මන්නාරම': 'mannar',
    'වවුනියාව': 'vavuniya',
    'වව්නියාව': 'vavuniya',
    'මුලතිව්': 'mullaitivu',
    'මඩකලපුව': 'batticaloa',
    'අම්පාර': 'ampara',
    'ත්‍රිකුණාමලය': 'trincomalee',
    'කුරුණෑගල': 'kurunegala',
    'පුත්තලම': 'puttalam',
    'අනුරාධපුරය': 'anuradhapura',
    'පොළොන්නරුව': 'polonnaruwa',
    'බදුල්ල': 'badulla',
    'මොණරාගල': 'monaragala',
    'රත්නපුර': 'ratnapura',
    'කෑගල්ල': 'kegalle',

    // Tamil
    'கொழும்பு': 'colombo',
    'கம்பஹா': 'gampaha',
    'களுத்துறை': 'kalutara',
    'கண்டி': 'kandy',
    'மாத்தளை': 'matale',
    'நுவரெலியா': 'nuwara_eliya',
    'காலி': 'galle',
    'மாத்தறை': 'matara',
    'ஹம்பாந்தோட்டை': 'hambantota',
    'யாழ்ப்பாணம்': 'jaffna',
    'கிளிநொச்சி': 'kilinochchi',
    'மன்னார்': 'mannar',
    'வவுனியா': 'vavuniya',
    'முல்லைத்தீவு': 'mullaitivu',
    'மட்டக்களப்பு': 'batticaloa',
    'அம்பாறை': 'ampara',
    'திருகோணமலை': 'trincomalee',
    'குருநாகல்': 'kurunegala',
    'புத்தளம்': 'puttalam',
    'அனுராதபுரம்': 'anuradhapura',
    'பொலன்னறுவை': 'polonnaruwa',
    'பதுளை': 'badulla',
    'மொனராகலை': 'monaragala',
    'இரத்தினபுரி': 'ratnapura',
    'கேகாலை': 'kegalle'
};

export const getDistrictKey = (value: string): string | null => {
    if (!value) return null;
    const normalized = value.toLowerCase().trim();
    return DISTRICT_KEY_MAP[normalized] || null;
};
