export const DISTRICTS = {
    si: [
        { value: 'colombo', label: 'කොළඹ' },
        { value: 'gampaha', label: 'ගම්පහ' },
        { value: 'kalutara', label: 'කළුතර' },
        { value: 'kandy', label: 'මහනුවර' },
        { value: 'matale', label: 'මාතලේ' },
        { value: 'nuwara-eliya', label: 'නුවර එළිය' },
        { value: 'galle', label: 'ගාල්ල' },
        { value: 'matara', label: 'මාතර' },
        { value: 'hambantota', label: 'හම්බන්තොට' },
        { value: 'jaffna', label: 'යාපනය' },
        { value: 'kilinochchi', label: 'කිලිනොච්චි' },
        { value: 'mannar', label: 'මන්නාරම' },
        { value: 'vavuniya', label: 'වව්නියාව' },
        { value: 'mullaitivu', label: 'මුලතිව්' },
        { value: 'batticaloa', label: 'මඩකලපුව' },
        { value: 'ampara', label: 'අම්පාර' },
        { value: 'trincomalee', label: 'ත්‍රිකුණාමලය' },
        { value: 'kurunegala', label: 'කුරුණෑගල' },
        { value: 'puttalam', label: 'පුත්තලම' },
        { value: 'anuradhapura', label: 'අනුරාධපුරය' },
        { value: 'polonnaruwa', label: 'පොළොන්නරුව' },
        { value: 'badulla', label: 'බදුල්ල' },
        { value: 'monaragala', label: 'මොණරාගල' },
        { value: 'ratnapura', label: 'රත්නපුර' },
        { value: 'kegalle', label: 'කෑගල්ල' },
    ],
    en: [
        { value: 'colombo', label: 'Colombo' },
        { value: 'gampaha', label: 'Gampaha' },
        { value: 'kalutara', label: 'Kalutara' },
        { value: 'kandy', label: 'Kandy' },
        { value: 'matale', label: 'Matale' },
        { value: 'nuwara-eliya', label: 'Nuwara Eliya' },
        { value: 'galle', label: 'Galle' },
        { value: 'matara', label: 'Matara' },
        { value: 'hambantota', label: 'Hambantota' },
        { value: 'jaffna', label: 'Jaffna' },
        { value: 'kilinochchi', label: 'Kilinochchi' },
        { value: 'mannar', label: 'Mannar' },
        { value: 'vavuniya', label: 'Vavuniya' },
        { value: 'mullaitivu', label: 'Mullaitivu' },
        { value: 'batticaloa', label: 'Batticaloa' },
        { value: 'ampara', label: 'Ampara' },
        { value: 'trincomalee', label: 'Trincomalee' },
        { value: 'kurunegala', label: 'Kurunegala' },
        { value: 'puttalam', label: 'Puttalam' },
        { value: 'anuradhapura', label: 'Anuradhapura' },
        { value: 'polonnaruwa', label: 'Polonnaruwa' },
        { value: 'badulla', label: 'Badulla' },
        { value: 'monaragala', label: 'Monaragala' },
        { value: 'ratnapura', label: 'Ratnapura' },
        { value: 'kegalle', label: 'Kegalle' },
    ],
    ta: [
        { value: 'colombo', label: 'கொழும்பு' },
        { value: 'gampaha', label: 'கம்பஹா' },
        { value: 'kalutara', label: 'களுத்துறை' },
        { value: 'kandy', label: 'கண்டி' },
        { value: 'matale', label: 'மாத்தளை' },
        { value: 'nuwara-eliya', label: 'நுவரெலியா' },
        { value: 'galle', label: 'காலி' },
        { value: 'matara', label: 'மாத்தறை' },
        { value: 'hambantota', label: 'அம்பாந்தோட்டை' },
        { value: 'jaffna', label: 'யாழ்ப்பாணம்' },
        { value: 'kilinochchi', label: 'கிளிநொச்சி' },
        { value: 'mannar', label: 'மன்னார்' },
        { value: 'vavuniya', label: 'வவுனியா' },
        { value: 'mullaitivu', label: 'முல்லைத்தீவு' },
        { value: 'batticaloa', label: 'மட்டக்களப்பு' },
        { value: 'ampara', label: 'அம்பாறை' },
        { value: 'trincomalee', label: 'திருகோணமலை' },
        { value: 'kurunegala', label: 'குருநாகல்' },
        { value: 'puttalam', label: 'புத்தளம்' },
        { value: 'anuradhapura', label: 'அனுராதபுரம்' },
        { value: 'polonnaruwa', label: 'பொலன்னறுவை' },
        { value: 'badulla', label: 'பதுளை' },
        { value: 'monaragala', label: 'மொணராகலை' },
        { value: 'ratnapura', label: 'இரத்தினபுரி' },
        { value: 'kegalle', label: 'கேகாலை' },
    ],
};

export const getDistrictLabel = (value: string, language: 'si' | 'en' | 'ta' = 'si') => {
    const district = DISTRICTS[language].find(d => d.value === value);
    return district ? district.label : value;
};

export const getDistricts = (language: 'si' | 'en' | 'ta' = 'si') => {
    return DISTRICTS[language];
};
